name: Pipeline

on:
  push:
    branches:
      - 'master'

env:
  TEMPLATE_NAME: template.yaml
  PROD_PIPELINE_EXECUTION_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/administrator
  PROD_STACK_NAME: root-infrastructure

jobs:
  deploy-production:
    name: Deploy to production
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ env.PROD_PIPELINE_EXECUTION_ROLE }}
          role-session-name: prod-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy production infrastructure
        shell: bash
        run: |
          sam deploy --stack-name ${{ env.PROD_STACK_NAME }} \
            --template-file ${{ env.TEMPLATE_NAME }} \
            --region ${{ secrets.AWS_REGION }} \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_NAMED_IAM

  bump:
    name: Bump the version number and tag the commit
    needs: [deploy-production]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Install Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Set git name and email
        run: |
          git config --local user.email "dbowland1+bot@gmail.com"
          git config --local user.name "github-actions[bot]"
      - name: Bump the minor version
        run: npm version minor
      - name: Push tag created by version bump
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
